---
version: "3.8"
services:
  app:
    build:
      args:
        IMAGE_VARIANT: ${DEV_CONTAINER_IMAGE_VARIANT:-3.8-bullseye}
        POETRY_VERSION: ${DEV_CONTAINER_POETRY_VERSION:-1.3.2}
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - .:/app:cache
      - /app/.venv
      - ~/.bash_history:/home/vscode/.bash_history:cache
      - extensions-cache:/home/vscode/.vscode-server/extensions:cache

volumes:
  extensions-cache:
