---
version: "3.8"
x-app: &default-app
  build:
    dockerfile: Dockerfile
  restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
  tty: true

services:
  postgres:
    env_file:
      - .env
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      timeout: 5s
    image: ${DB_IMAGE:-postgres:14.4-bullseye}
    init: true
    ports:
      - 5432:5432
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    stop_grace_period: 3s

volumes:
  postgres:
