version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  lint:
    docker:
      - image: cimg/python:3.8.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - lint-cache-{{ checksum ".pre-commit-config.yaml" }}
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Lint
          command: poetry run pre-commit run --all
      - save_cache:
          paths:
            - /home/circleci/project/.venv
            - ~/.cache/pre-commit
          key: lint-cache-{{ checksum ".pre-commit-config.yaml" }}
  test:
    docker:
      - image: cimg/python:3.8.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - venvs-cache
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run nox -r
      - save_cache:
          paths:
            - /home/circleci/project/.nox
            - /home/circleci/project/.venv
          key: venvs-cache
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov

workflows:
  sample:
    jobs:
      - lint
      - test
