version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
  python: circleci/python@1.5.0

parameters:
  cache-version:
    type: integer
    default: 3
  image-tag:
    type: string
    default: 3.8.16
  nox-envs-path:
    type: string
    default: /home/circleci/project/.nox
  venv-path:
    type: string
    default: /home/circleci/project/.venv

jobs:
  docs:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - docs-cache-v<< pipeline.parameters.cache-version >>-{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run
          command: poetry run nox -s docs xdoctest
      - save_cache:
          paths:
            - << pipeline.parameters.nox-envs-path >>
            - << pipeline.parameters.venv-path >>
          key: docs-cache-v<< pipeline.parameters.cache-version >>-{{ checksum "poetry.lock" }}
      - store_artifacts:
          path: docs/_build
  lint:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - lint-cache-v<< pipeline.parameters.cache-version >>-{{ checksum ".pre-commit-config.yaml" }}
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run
          command: poetry run pre-commit run --all
      - save_cache:
          paths:
            - << pipeline.parameters.venv-path >>
            - ~/.cache/pre-commit
          key: lint-cache-v<< pipeline.parameters.cache-version >>-{{ checksum ".pre-commit-config.yaml" }}
  security:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - security-cache-v<< pipeline.parameters.cache-version >>-{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run
          command: poetry run nox -s safety
      - save_cache:
          paths:
            - << pipeline.parameters.nox-envs-path >>
            - << pipeline.parameters.venv-path >>
          key: security-cache-v<< pipeline.parameters.cache-version >>-{{ checksum "poetry.lock" }}
  test:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >>
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - test-cache-v<< pipeline.parameters.cache-version >>-{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
            echo $TEST_FILES
            poetry run nox -- -s tests -- $TEST_FILES
      - save_cache:
          paths:
            - << pipeline.parameters.nox-envs-path >>
            - << pipeline.parameters.venv-path >>
          key: test-cache-v<< pipeline.parameters.cache-version >>-{{ checksum "poetry.lock" }}
      - store_test_results:
          path: test-results
  typing:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >>
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - typing-cache-v<< pipeline.parameters.cache-version >>-{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
            poetry run nox -- -s typeguard -- $TEST_FILES
      - save_cache:
          paths:
            - << pipeline.parameters.nox-envs-path >>
            - << pipeline.parameters.venv-path >>
          key: typing-cache-v<< pipeline.parameters.cache-version >>-{{ checksum "poetry.lock" }}

workflows:
  upload-to-codecov:
    jobs:
      - docs:
          context:
            - context
      - lint:
          context:
            - context
      - security:
          context:
            - context
      - test:
          context:
            - context
      - typing:
          context:
            - context
