---
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
  python: circleci/python@1.5.0

parameters:
  cache-version:
    type: integer
    default: 4
  image-tag:
    type: string
    default: 3.8.16
  poetry-hash-path:
    type: string
    default: /home/circleci/project/poetry.lock.sha256
  nox-envs-path:
    type: string
    default: /home/circleci/project/.nox
  venv-path:
    type: string
    default: /home/circleci/project/.venv

executors:
  python-executor:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >> # context / project UI env-var reference

jobs:
  test:
    executor: python-executor
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              test-cache
              -v<< pipeline.parameters.cache-version >>
              -{{ checksum "poetry.lock" }}
      - run:
          name: Run
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | \
              circleci tests split --split-by=timings)
            echo $TEST_FILES
            poetry run nox -- -s tests -- -m "not e2e" --cov-fail-under=0 \
              --cov-report xml:coverage.xml $TEST_FILES
            mkdir -p workspace
            cp .coverage workspace/.coverage.$CIRCLE_NODE_INDEX
            ls -al
            ls -al workspace/
      - persist_to_workspace:
          root: workspace
          paths:
            - ./*
      - run:
          name: Upload to codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov --file /home/circleci/project/coverage.xml
      - store_test_results:
          path: test-results
      - save_cache:
          paths:
            - << pipeline.parameters.nox-envs-path >>
            - << pipeline.parameters.poetry-hash-path >>
            - << pipeline.parameters.venv-path >>
          key: >-
            test-cache
            -v<< pipeline.parameters.cache-version >>
            -{{ checksum "poetry.lock" }}
  coverage:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              test-cache
              -v<< pipeline.parameters.cache-version >>
              -{{ checksum "poetry.lock" }}
      - attach_workspace:
          at: workspace
      - run:
          name: Run
          command: poetry run nox -- -s coverage -- combine
  docs:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              docs-cache
              -v<< pipeline.parameters.cache-version >>
              -{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - save_cache:
          paths:
            - << pipeline.parameters.nox-envs-path >>
            - << pipeline.parameters.poetry-hash-path >>
            - << pipeline.parameters.venv-path >>
          key: >-
            docs-cache
            -v<< pipeline.parameters.cache-version >>
            -{{ checksum "poetry.lock" }}
      - run:
          name: Run
          command: poetry run nox -s docs xdoctest
      - store_artifacts:
          path: docs/_build
  lint:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              lint-cache
              -v<< pipeline.parameters.cache-version >>
              -{{ checksum ".pre-commit-config.yaml" }}
      - python/install-packages:
          pkg-manager: poetry
      - save_cache:
          paths:
            - << pipeline.parameters.venv-path >>
            - << pipeline.parameters.poetry-hash-path >>
            - ~/.cache/pre-commit
          key: >-
            lint-cache
            -v<< pipeline.parameters.cache-version >>
            -{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run
          command: poetry run pre-commit run --all
  security:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              security-cache
              -v<< pipeline.parameters.cache-version >>
              -{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - save_cache:
          paths:
            - << pipeline.parameters.nox-envs-path >>
            - << pipeline.parameters.poetry-hash-path >>
            - << pipeline.parameters.venv-path >>
          key: >-
            security-cache
            -v<< pipeline.parameters.cache-version >>
            -{{ checksum "poetry.lock" }}
      - run:
          name: Run
          command: poetry run nox -- -s safety -- -i 51668 -i 51457
  typing:
    docker:
      - image: cimg/python:<< pipeline.parameters.image-tag >>
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              typing-cache
              -v<< pipeline.parameters.cache-version >>
              -{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - save_cache:
          paths:
            - << pipeline.parameters.nox-envs-path >>
            - << pipeline.parameters.poetry-hash-path >>
            - << pipeline.parameters.venv-path >>
          key: >-
            typing-cache
            -v<< pipeline.parameters.cache-version >>
            -{{ checksum "poetry.lock" }}
      - run:
          name: Run
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | \
              circleci tests split --split-by=timings)
            poetry run nox -- -s typeguard -- $TEST_FILES

workflows:
  upload-to-codecov:
    jobs:
      - test:
          context:
            - context
      - coverage:
          context:
            - context
          require:
            - test
      - docs:
          context:
            - context
      - lint:
          context:
            - context
      - security:
          context:
            - context
      - typing:
          context:
            - context
