version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  lint:
    docker:
      - image: cimg/python:3.8.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - venvs-cache
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Lint
          command: poetry run pre-commit run -a
      - save_cache:
          paths:
            - /home/circleci/project/.venv
          key: venvs-cache
  test:
    docker:
      - image: cimg/python:3.8.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - venvs-cache
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run nox -r
      - save_cache:
          paths:
            - /home/circleci/project/.nox
            - /home/circleci/project/.venv
          key: venvs-cache

workflows:
  sample:
    jobs:
      - lint
      - test
