---
services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  webpi:
    build:
      args:
        IMAGE:
          "${WEBPI_IMAGE:-tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim}"
    extends:
      file: docker-compose.yml
      service: web

volumes:
  postgres: {}
