---
services:
  app:
    build:
      args:
        VARIANT: ${DEV_IMAGE_VARIANT:-3.8-bullseye}
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    volumes:
      - ~/.bash_history:/home/vscode/.bash_history:cache
      - ~/.gitconfig:/home/vscode/.gitconfig
      - extensions-cache:/home/vscode/.vscode-server/extensions:cache
      - home-cache:/home/vscode/.cache:cache

volumes:
  home-cache:
  extensions-cache:
